from __future__ import annotations

from tests.integration.observability.render.case_types import CaseData
from tests.integration.observability.render.status_case_builders import (
    build_cascading_failure_workflow,
    build_failure_propagation_workflow,
    build_partial_failure_workflow,
    build_pending_running_succeeded_workflow,
)
from tests.integration.observability.render.topology_case_builders import (
    build_asymmetric_fanout_workflow,
    build_diamond_workflow,
    build_fanout_chain_fanin_workflow,
    build_independent_roots_fanin_workflow,
    build_independent_subgraphs_workflow,
    build_linear_chain_workflow,
    build_nested_fanout_workflow,
    build_overflow_workflow,
    build_parallel_chain_sidecar_workflow,
    build_parallel_roots_workflow,
    build_single_node_workflow,
)

TOPOLOGY_CASES: tuple[CaseData, ...] = (
    {
        "case_id": "single-node",
        "build_workflow": build_single_node_workflow,
        "snapshot_event_type": "workflow_finished",
        "selected_node_id": "backend.deploy",
        "expected_fragments": ("backend.deploy", "✅", "codex"),
    },
    {
        "case_id": "fully-parallel-roots",
        "build_workflow": build_parallel_roots_workflow,
        "snapshot_event_type": "workflow_finished",
        "selected_node_id": "backend.billing",
        "expected_fragments": (
            "backend.auth",
            "backend.billing",
            "backend.payments",
            "frontend.ui",
        ),
    },
    {
        "case_id": "linear-chain",
        "build_workflow": build_linear_chain_workflow,
        "snapshot_event_type": "workflow_finished",
        "selected_node_id": "design.iteration",
        "expected_fragments": (
            "design.discovery",
            "design.iteration",
            "design.decision",
            "codex",
        ),
    },
    {
        "case_id": "fanout-chain-fanin",
        "build_workflow": build_fanout_chain_fanin_workflow,
        "snapshot_event_type": "workflow_finished",
        "selected_node_id": "implement.review",
        "expected_fragments": (
            "implement.plan",
            "implement.build",
            "implement.review",
            "implement.fixes",
            "implement.handoff",
        ),
    },
    {
        "case_id": "diamond",
        "build_workflow": build_diamond_workflow,
        "snapshot_event_type": "workflow_finished",
        "selected_node_id": "data.transform",
        "expected_fragments": (
            "data.extract",
            "data.transform",
            "data.validate",
            "data.load",
        ),
    },
    {
        "case_id": "fanin-independent-roots",
        "build_workflow": build_independent_roots_fanin_workflow,
        "snapshot_event_type": "workflow_finished",
        "selected_node_id": "gateway.compose",
        "expected_fragments": (
            "service.auth",
            "service.billing",
            "service.cache",
            "gateway.compose",
        ),
    },
    {
        "case_id": "parallel-branches-with-side-chain",
        "build_workflow": build_parallel_chain_sidecar_workflow,
        "snapshot_event_type": "workflow_finished",
        "selected_node_id": "impl.api-test",
        "expected_fragments": (
            "plan",
            "impl.api",
            "impl.api-test",
            "impl.frontend",
            "impl.docs",
            "release",
        ),
    },
    {
        "case_id": "asymmetric-fanout",
        "build_workflow": build_asymmetric_fanout_workflow,
        "snapshot_event_type": "workflow_finished",
        "selected_node_id": "deploy.backend",
        "expected_fragments": (
            "design",
            "build.backend",
            "test.backend",
            "deploy.backend",
            "build.frontend",
            "gemini, claude",
            "integration",
        ),
    },
    {
        "case_id": "multiple-independent-subgraphs",
        "build_workflow": build_independent_subgraphs_workflow,
        "snapshot_event_type": "workflow_finished",
        "selected_node_id": "backend.deploy",
        "expected_fragments": (
            "backend.api",
            "frontend.build",
            "backend.deploy",
            "frontend.deploy",
        ),
    },
    {
        "case_id": "nested-fanout",
        "build_workflow": build_nested_fanout_workflow,
        "snapshot_event_type": "workflow_finished",
        "selected_node_id": "impl.tests",
        "expected_fragments": (
            "plan",
            "impl.frontend",
            "impl.tests",
            "impl.backend",
            "review",
        ),
    },
    {
        "case_id": "overflow-cap",
        "build_workflow": build_overflow_workflow,
        "snapshot_event_type": "workflow_finished",
        "selected_node_id": "root",
        "expected_fragments": (
            "root",
            "merge",
        ),
    },
)
STATUS_CASES: tuple[CaseData, ...] = (
    {
        "case_id": "pending-running-succeeded-snapshot",
        "build_workflow": build_pending_running_succeeded_workflow,
        "snapshot_event_type": "node_started",
        "snapshot_node_id": "deploy.api",
        "selected_node_id": "deploy.api",
        "expected_fragments": (
            "setup.infra",
            "deploy.api",
            "verify.e2e",
            "✅",
            "⏳",
            "⏸",
        ),
    },
    {
        "case_id": "failure-propagation",
        "build_workflow": build_failure_propagation_workflow,
        "snapshot_event_type": "workflow_failed",
        "selected_node_id": "compile.api",
        "mock_options": {
            "fail_when": [{"node_id": "compile.api"}],
        },
        "expect_error": "compile.api",
        "expected_fragments": (
            "compile.api",
            "deploy.api",
            "❌",
            "⛔  blocked",
        ),
    },
    {
        "case_id": "cascading-failure",
        "build_workflow": build_cascading_failure_workflow,
        "snapshot_event_type": "workflow_failed",
        "selected_node_id": "infra.provision",
        "mock_options": {
            "fail_when": [{"node_id": "infra.provision"}],
        },
        "expect_error": "infra.provision",
        "expected_fragments": (
            "infra.provision",
            "app.deploy",
            "smoke.test",
            "❌",
            "⛔  blocked",
        ),
    },
    {
        "case_id": "partial-failure-in-fanout",
        "build_workflow": build_partial_failure_workflow,
        "snapshot_event_type": "workflow_failed",
        "selected_node_id": "build.worker",
        "mock_options": {
            "fail_when": [{"node_id": "build.worker"}],
        },
        "expect_error": "build.worker",
        "expected_fragments": (
            "build.plan",
            "build.api",
            "build.worker",
            "❌",
            "build.integrate",
            "⛔  blocked",
        ),
    },
)
