"""Capture comparable platform contracts against an installed source revision.

Run with that revision's Python and PYTHONPATH, reusing the same empty project
path between captures. Normalization is restricted to run IDs, ISO timestamps,
elapsed-time fields, process IDs/groups, and the temporary project root. Exact
provider/generated bytes and every persisted artifact descriptor are verified
before normalization; workflow signatures and exception chains are retained.
Event comparison uses a multiset because parallel completion order is unspecified.
Summary rows for the two parallel invocations are sorted within each section.
Run-directory timestamps are fixed before execution so collision suffixes cannot
change review-prompt lengths and their visible-token estimates.
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import os
import re
import subprocess
import sys
from dataclasses import asdict
from datetime import datetime
from pathlib import Path
from unittest.mock import patch

import yaml
from typer.testing import CliRunner

from crewplane.adapters.invokers.mock_invoker.invoker import MockAgentInvoker
from crewplane.architecture.contracts import InvocationContext
from crewplane.artifacts.atomic import atomic_write_bytes_if_absent
from crewplane.cli.app import app
from crewplane.runtime.agent.invocation.command import run_command_once
from tests.helpers.installed_wheel_smoke import verify_run
from tests.helpers.mock_resume import write_executor_fixture
from tests.helpers.review_checkpoint_cli import write_checkpoint_project

ISO_TIMESTAMP = re.compile(
    r"\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:[+-]\d{2}:\d{2}|Z)?"
)
ELAPSED_TEXT = re.compile(r"\b\d+(?:\.\d+)?s\b")
GENERATED_BYTES = "generated café\r\ncontrol-Z\x1a\n".encode()


def normalized_text(text: str, project: Path, run_id: str = "") -> str:
    text = text.replace(str(project), "<project>")
    if run_id:
        text = text.replace(run_id, "<run-id>")
    return ELAPSED_TEXT.sub("<elapsed>", ISO_TIMESTAMP.sub("<timestamp>", text))


def normalized_summary(text: str, project: Path, run_id: str) -> str:
    sections = re.split(r"(\r?\n\r?\n)", normalized_text(text, project, run_id))
    for index in range(0, len(sections), 2):
        lines = re.split(r"(\r?\n)", sections[index])
        parallel_indices = [
            position
            for position in range(0, len(lines), 2)
            if lines[position].startswith("- `fanout` /")
        ]
        parallel_rows = sorted(lines[position] for position in parallel_indices)
        for position, row in zip(parallel_indices, parallel_rows, strict=True):
            lines[position] = row
        sections[index] = "".join(lines)
    return "".join(sections)


def invoke(arguments: list[str]) -> str:
    result = CliRunner().invoke(app, arguments)
    assert result.exit_code == 0, (arguments, result.output, result.exception)
    return result.output


def prepare_project(project: Path) -> tuple[Path, Path]:
    fixtures = project / "fixtures"
    config, workflow = write_checkpoint_project(project, fixtures, predecessor=True)
    configuration = yaml.safe_load(config.read_bytes())
    # A mock command is never executed; keep its signature independent of venv paths.
    configuration["agents"]["alpha"]["cli_cmd"] = ["platform-probe-provider"]
    configuration["settings"]["workspace"] = {"enabled": False}
    config.write_text(yaml.safe_dump(configuration), encoding="utf-8")
    _, frontmatter, sections = workflow.read_text().split("---", 2)
    specification = yaml.safe_load(frontmatter)
    specification["nodes"].append(
        {
            "id": "fanout",
            "mode": "parallel",
            "needs": ["after"],
            "providers": ["alpha", "alpha"],
        }
    )
    workflow.write_text(
        "---\n"
        + yaml.safe_dump(specification)
        + "---"
        + sections
        + "\n## fanout\nParallel results.\n",
        encoding="utf-8",
    )
    write_executor_fixture(
        fixtures, "after", "## Generated Files\n\n[report](report.bin)\n"
    )
    for index in range(2):
        fixture = fixtures / "fanout" / f"alpha_executor_{index}_round1.md"
        fixture.parent.mkdir(exist_ok=True)
        fixture.write_bytes(f"Parallel result {index}.\n".encode())
    subprocess.run(["git", "init", "-q", str(project)], check=True, timeout=30)
    return config, workflow


def capture_run(project: Path, stage: Path) -> dict[str, object]:
    verify_run(project, stage)
    manifest = json.loads((stage / "manifests/run.json").read_bytes())
    results = project / ".crewplane/execution-results" / stage.name
    captured = list(results.rglob("report.bin"))
    assert captured and all(path.read_bytes() == GENERATED_BYTES for path in captured)
    checkpoints = list((stage / "manifests/review-checkpoints").glob("*.json"))
    assert checkpoints
    normalized_results = {
        path.relative_to(results).as_posix(): normalized_text(
            path.read_bytes().decode("utf-8"), project, manifest["run_id"]
        )
        for path in sorted(results.rglob("*.md"))
    }
    nodes = {}
    for path in sorted((stage / "manifests/nodes").glob("*.json")):
        state = json.loads(path.read_bytes())
        nodes[path.name] = {
            key: state.get(key) for key in ("status", "node_id", "resume_origin")
        }
    events = [
        json.loads(line)
        for line in (stage / "logs/events.ndjson").read_text().splitlines()
    ]
    # Parallel scheduling order is unspecified; compare the event multiset.
    event_counts: dict[str, int] = {}
    for event in events:
        event_key = json.dumps(
            {
                key: value
                for key, value in event.items()
                if key
                not in {
                    "timestamp",
                    "elapsed_seconds",
                    "duration_seconds",
                    "duration_ms",
                    "run_id",
                    "sequence",
                }
            },
            sort_keys=True,
        )
        event_key = normalized_text(event_key, project, manifest["run_id"])
        event_counts[event_key] = event_counts.get(event_key, 0) + 1
    return {
        "status": manifest["status"],
        "workflow_signature": manifest["workflow_signature"],
        "nodes": nodes,
        "results": normalized_results,
        "generated_sha256": hashlib.sha256(GENERATED_BYTES).hexdigest(),
        "generated_count": len(captured),
        "review_checkpoints": len(checkpoints),
        "events": event_counts,
        "summary": normalized_summary(
            (stage / "logs/summary.md").read_bytes().decode("utf-8"),
            project,
            manifest["run_id"],
        ),
    }


async def capture_process(project: Path) -> dict[str, object]:
    events = []
    context = InvocationContext(
        "node", "task", "generic", "executor", process_event_sink=events.append
    )
    result = await run_command_once(
        [
            sys.executable,
            "-c",
            "import sys; sys.stdout.buffer.write(b'exact\\r\\n\\x1a\\xff'); sys.stderr.buffer.write(b'diagnostic\\n')",
        ],
        None,
        project / "provider.log",
        False,
        b"header\n",
        project,
        context,
        None,
    )
    try:
        assert result.stdout_path is not None and result.stderr_path is not None
        streams = {
            "stdout": result.stdout_path.read_bytes().hex(),
            "stderr": result.stderr_path.read_bytes().hex(),
        }
    finally:
        result.cleanup_stream_files()
    receipts = []
    for event in events:
        receipt = asdict(event)
        receipt["process_group_id"] = (
            "leader" if event.process_group_id == event.pid else None
        )
        receipt["pid"] = "<pid>"
        receipts.append(receipt)
    try:
        missing_result = await run_command_once(
            ["crewplane-platform-probe-missing-command"],
            None,
            None,
            False,
            None,
            project,
            None,
            None,
        )
    except RuntimeError as exc:
        failure = {
            "type": type(exc).__name__,
            "message": str(exc),
            "cause": type(exc.__cause__).__name__,
            "cause_message": str(exc.__cause__),
        }
    else:
        try:
            assert missing_result.returncode == 127
            assert missing_result.stdout_path is not None
            assert missing_result.stderr_path is not None
            failure = {
                "returncode": missing_result.returncode,
                "stdout": missing_result.stdout_path.read_bytes().hex(),
                "stderr": missing_result.stderr_path.read_bytes().hex(),
            }
        finally:
            missing_result.cleanup_stream_files()
    return {
        "streams": streams,
        "receipts": receipts,
        "log": (project / "provider.log").read_bytes().hex(),
        "failure": failure,
    }


def capture(project: Path) -> dict[str, object]:
    config, workflow = prepare_project(project)
    command = ["run", "--tasks", str(workflow), "--config", str(config), "--no-live"]
    original = MockAgentInvoker.invoke

    async def create_report(self, *args, **kwargs):
        context = kwargs.get("invocation_context")
        if context is not None and context.node_id == "after":
            (project / "report.bin").write_bytes(GENERATED_BYTES)
        return await original(self, *args, **kwargs)

    snapshot = set(project.rglob("*"))
    validation = invoke(["validate", str(workflow), "--config", str(config)])
    dry_run = invoke([*command, "--dry-run"])
    assert set(project.rglob("*")) == snapshot
    with (
        patch.object(MockAgentInvoker, "invoke", new=create_report),
        patch(
            "crewplane.artifacts.directory_manager.datetime", wraps=datetime
        ) as clock,
    ):
        clock.now.side_effect = [datetime(2026, 10, 9), datetime(2026, 10, 9, 0, 1)]
        invoke(command)
        stages = project / ".crewplane/execution-stages"
        first = next(stages.iterdir())
        first_capture = capture_run(project, first)
        dedupe = invoke(command)
        assert "Identical context detected" in dedupe
        assert len(list(stages.iterdir())) == 1
        (project / "report.bin").unlink()
        invoke([*command, "--force"])
        second = next(path for path in stages.iterdir() if path != first)
        forced_capture = capture_run(project, second)
        assert (
            first_capture["workflow_signature"] == forced_capture["workflow_signature"]
        )
    occupied = project / "occupied"
    atomic_write_bytes_if_absent(occupied, b"original")
    try:
        atomic_write_bytes_if_absent(occupied, b"replacement")
    except FileExistsError:
        pass
    else:
        raise AssertionError("Occupied destination was replaced")
    assert occupied.read_bytes() == b"original"
    assert not list((project / ".crewplane/locks").iterdir())
    return {
        "validation": normalized_text(validation, project),
        "dry_run": normalized_text(dry_run, project),
        "first": first_capture,
        "forced": forced_capture,
        "process": asyncio.run(capture_process(project)),
        "locks_empty": True,
        "collision_preserved": True,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    project = args.project.resolve()
    project.mkdir()
    os.chdir(project)
    result = capture(project)
    args.output.resolve().write_text(
        json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
