name: scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: "31 8 * * 1"
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

concurrency:
  group: scorecard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scorecard:
    name: OpenSSF Scorecard
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Run analysis
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: false

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@e4fba868fa4b1b91e1fdab776edc8cfbe6e9fb81 # v4
        with:
          sarif_file: results.sarif
